 version: 2
 jobs:
   build:
    working_directory: /go/src/github.com/licaonfee/ratchet
    docker:
      - image: circleci/golang:1.13
    steps:
      - checkout
      - run: 
          name: test
          command: |
            go get -v .
            echo $PWD
            go test -timeout 30s ./... 